// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfs2ZGXIPcoW9I6BBsbKzymSv_gmFfhbU',
    appId: '1:109908259887:web:752751f6b92d86dff9c2da',
    messagingSenderId: '109908259887',
    projectId: 'inlabactivity-7285f',
    authDomain: 'inlabactivity-7285f.firebaseapp.com',
    databaseURL: 'https://inlabactivity-7285f-default-rtdb.firebaseio.com',
    storageBucket: 'inlabactivity-7285f.appspot.com',
    measurementId: 'G-K6V36M38KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWphoUeGiXFO6UweLdpIiRmKqk_J17Co',
    appId: '1:109908259887:android:b4a0fe0b79abcb09f9c2da',
    messagingSenderId: '109908259887',
    projectId: 'inlabactivity-7285f',
    databaseURL: 'https://inlabactivity-7285f-default-rtdb.firebaseio.com',
    storageBucket: 'inlabactivity-7285f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlEhevjrucmb9tDfXhKOl_9woTUP5eE0',
    appId: '1:109908259887:ios:21008b5b65269bf9f9c2da',
    messagingSenderId: '109908259887',
    projectId: 'inlabactivity-7285f',
    databaseURL: 'https://inlabactivity-7285f-default-rtdb.firebaseio.com',
    storageBucket: 'inlabactivity-7285f.appspot.com',
    iosClientId: '109908259887-4ijaijfmoauemv1tr0phm00i66b9ikmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInLabActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZlEhevjrucmb9tDfXhKOl_9woTUP5eE0',
    appId: '1:109908259887:ios:21008b5b65269bf9f9c2da',
    messagingSenderId: '109908259887',
    projectId: 'inlabactivity-7285f',
    databaseURL: 'https://inlabactivity-7285f-default-rtdb.firebaseio.com',
    storageBucket: 'inlabactivity-7285f.appspot.com',
    iosClientId: '109908259887-4ijaijfmoauemv1tr0phm00i66b9ikmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInLabActivity',
  );
}
